- client/src/main/java/ru/hh/jclient/common/RequestBuilder.java
AsyncHttpClient как ненормальный сыпет ворнингами Value was null, set to ""
> HH-86256 remove excessive warnings in addHeader

- client/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- client/src/main/java/ru/hh/jclient/common/balancing/Server.java
- client/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
https://jira.hh.ru/browse/HH-86898
> HH-86898 fix adaptive servers gathering

- client/src/main/java/ru/hh/jclient/common/RequestBuilder.java
https://jira.hh.ru/browse/HH-88994
> HH-88994 add 'addBodyPart' to RequestBuilder

- .travis.yml
- README.md
- client-tests/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-89356
> HH-89356 Add SonarCloud integration

- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- jclient-common-api/src/main/java/ru/hh/jclient/common/HttpHeaderNames.java
https://jira.hh.ru/browse/HH-92107
> HH-92107 revert passing hh-analytics header

- client-tests/src/test/java/ru/hh/jclient/common/HttpClientTest.java
- client/src/main/java/ru/hh/jclient/common/HttpClient.java
- client/src/main/java/ru/hh/jclient/common/responseconverter/JsonCollectionConverter.java
- client/src/main/java/ru/hh/jclient/common/responseconverter/JsonMapConverter.java
- client/src/main/java/ru/hh/jclient/common/util/JsonTypeConverter.java
https://github.com/hhru/jclient-common/pull/95 оформляем как задачу
> HH-93594 generic types for json collections

- client/src/main/java/ru/hh/jclient/common/HttpClient.java
- client/src/main/java/ru/hh/jclient/common/UpstreamManager.java
- client/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategy.java
- client/src/main/java/ru/hh/jclient/common/balancing/BalancingUpstreamManager.java
- client/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- client/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
https://jira.hh.ru/browse/HH-95634
> HH-95634 refactoring for search integration

- client-errors/pom.xml
- client-maven-enforcer/pom.xml
- client-metrics/pom.xml
- client-testbase/pom.xml
- client-testbase/src/main/java/ru/hh/jclient/common/HttpClientTestBase.java
- client-tests/pom.xml
- client-utils/pom.xml
- client/pom.xml
- client/src/main/java/ru/hh/jclient/common/HttpClient.java
- client/src/main/java/ru/hh/jclient/common/HttpClientContext.java
- client/src/main/java/ru/hh/jclient/common/HttpClientContextThreadLocalSupplier.java
- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- client/src/main/java/ru/hh/jclient/common/Request.java
- client/src/main/java/ru/hh/jclient/common/RequestContext.java
- client/src/main/java/ru/hh/jclient/common/ResultOrErrorProcessor.java
- client/src/main/java/ru/hh/jclient/common/ResultProcessor.java
- client/src/main/java/ru/hh/jclient/common/util/MoreFunctionalInterfaces.java
- client/src/main/java/ru/hh/jclient/common/util/storage/StorageUtils.java
- jclient-common-api/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-98726
> HH-98726 Allow to specify multiple request debug suppliers

- client-testbase/pom.xml
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTest.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTestBase.java
- client-tests/src/test/java/ru/hh/jclient/common/HttpClientTest.java
- client/src/main/java/ru/hh/jclient/common/HttpClient.java
- client/src/main/java/ru/hh/jclient/common/HttpClientFactory.java
- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- pom.xml
https://jira.hh.ru/browse/HH-99933
> HH-99933 clean up adaptive balancing

- client/src/main/java/ru/hh/jclient/common/responseconverter/ProtobufConverter.java
https://jira.hh.ru/browse/HH-109742
> HH-109742 [protobuf] return null if no content has been received

- balancing/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
https://jira.hh.ru/browse/HH-109910
> HH-109910 catch failed adaptive balancing

- balancing/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Server.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- client-metrics/src/main/java/ru/hh/jclient/common/metrics/KafkaUpstreamMonitoring.java
- client-metrics/src/main/java/ru/hh/jclient/common/metrics/UpstreamMonitoring.java
- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- client/src/main/java/ru/hh/jclient/common/Monitoring.java
- client/src/main/java/ru/hh/jclient/common/ResponseWrapper.java
https://jira.hh.ru/browse/HH-110129
> HH-110129 move to microseconds for timeToLastByte

- client/src/main/java/ru/hh/jclient/common/check/GlobalTimeoutCheck.java
https://jira.hh.ru/browse/HH-111435
> HH-111435: change error log to warn

- .hh-release.yaml
- client/src/main/java/ru/hh/jclient/common/util/MoreCompletableFutures.java
- pom.xml
https://jira.hh.ru/browse/HH-95438
Добавил метод, который позволяет дождаться нескольких фьюч в стиле fail-fast.
> HH-95438 add new method MoreCompletableFutures.allOrAnyExceptionallyOf()

- balancing/src/main/java/ru/hh/jclient/common/balancing/BalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Server.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- balancing/src/main/java/ru/hh/jclient/consul/UpstreamServiceImpl.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/ServerTest.java
- client-tests/src/test/java/ru/hh/jclient/consul/UpstreamServiceImplTest.java
https://jira.hh.ru/browse/HH-117868
> HH-117868 rollback data-center lower-casing for metrics

- balancing/src/main/java/ru/hh/jclient/common/balancing/BalancingUpstreamManager.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancerBuilder.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/UpstreamGroup.java
- balancing/src/main/java/ru/hh/jclient/consul/UpstreamServiceImpl.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/CustomizationBenchmark.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/UpstreamTest.java
- client/src/main/java/ru/hh/jclient/common/RequestBuilder.java
https://jira.hh.ru/browse/HH-118707
> HH-118707 move servers to upstream

- balancing/src/main/java/ru/hh/jclient/common/balancing/BalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/BalancingUpstreamManager.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Server.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/UpstreamConfig.java
- balancing/src/main/java/ru/hh/jclient/consul/UpstreamServiceImpl.java
- balancing/src/main/java/ru/hh/jclient/consul/model/Profile.java
- client-metrics/src/main/java/ru/hh/jclient/common/metrics/MonitoringRequestStrategyFactory.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTestBase.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/AbstractBalancingStrategyTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/BalancingUpstreamManagerTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/CustomizationBenchmark.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/ServerTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/UpstreamConfigParserTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/UpstreamTest.java
https://jira.hh.ru/browse/HH-121750
> Hh 121750 remove deactivation

- client-metrics/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-122730
> HH-122730 return compile scope for kafka-clients

- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
https://jira.hh.ru/browse/HH-129621
> HH-129621 don't pass X-Outer-Timeout-Ms for external requests

- client-tests/src/test/java/ru/hh/jclient/common/HttpClientTest.java
- client/src/main/java/ru/hh/jclient/common/HttpClient.java
- client/src/main/java/ru/hh/jclient/common/responseconverter/JsonConverter.java
https://jira.hh.ru/browse/HH-139929
> HH-139929 add expectJson for TypeReference

- client-maven-enforcer/pom.xml
- client-maven-enforcer/src/main/java/ru/hh/jclient/common/enforcer/JClientEnforcerMojo.java
https://jira.hh.ru/browse/HH-135767
> HH-135767 update jclient maven enforcer plugin

- client-errors/src/main/java/ru/hh/jclient/errors/impl/check/ApplyEmptyResultOperation.java
- client-errors/src/main/java/ru/hh/jclient/errors/impl/check/CheckedEmptyWithStatus.java
- client-errors/src/test/java/ru/hh/jclient/errors/MoreErrorsTest.java
https://jira.hh.ru/browse/HH-171814
> HH-171814 add CheckedEmptyWithStatus

- .hh-release.yaml
https://jira.hh.ru/browse/HH-172159
> HH-172159 activate changelog

- client/pom.xml
https://jira.hh.ru/browse/HH-175516
> HH-175516 up protobuf

- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- jclient-common-api/src/main/java/ru/hh/jclient/common/HttpHeaderNames.java
https://jira.hh.ru/browse/HH-176756
> HH-176756 pass tms session header

- balancing/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingState.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/BalancingState.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/ExternalUrlRequestor.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Server.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/UpstreamRequestBalancer.java
- client-metrics/src/main/java/ru/hh/jclient/common/metrics/KafkaUpstreamMonitoring.java
- client-metrics/src/main/java/ru/hh/jclient/common/metrics/UpstreamMonitoring.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/AbstractBalancingStrategyTest.java
- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- client/src/main/java/ru/hh/jclient/common/Monitoring.java
- client/src/main/java/ru/hh/jclient/common/ResponseWrapper.java
https://jira.hh.ru/browse/HH-167254
По сути только переименование. Важные места отметил.
Метрики поплыть не должны, они уже в миллисекундах отправлялись
> HH-167254 move from micros to millis

- client-tests/src/test/java/ru/hh/jclient/common/ContextBuilderTest.java
- client/src/main/java/ru/hh/jclient/common/HttpClientContextThreadLocalSupplier.java
- client/src/main/java/ru/hh/jclient/common/util/storage/StorageUtils.java
- client/src/main/java/ru/hh/jclient/common/util/storage/ThreadLocalStorage.java
https://jira.hh.ru/browse/HH-191037
> HH-191037 make HttpClientContextThreadLocalSupplier real supplier

- balancing/src/main/java/ru/hh/jclient/common/balancing/ExternalUrlRequestor.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancerBuilder.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/UpstreamRequestBalancer.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTestBase.java
- client-tests/src/test/java/ru/hh/jclient/common/HttpClientFactoryBuilderTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/RequestBalancerBuilderTest.java
- client/src/main/java/ru/hh/jclient/common/DefaultEngineBuilder.java
- client/src/main/java/ru/hh/jclient/common/HttpClientFactoryBuilder.java
- client/src/main/java/ru/hh/jclient/common/RequestEngineBuilder.java
https://jira.hh.ru/browse/HH-204486
> HH-204486 add setting for responses log level

- .hh-release.yaml
- balancing/src/main/java/ru/hh/jclient/common/balancing/ExternalUrlRequestor.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancerBuilder.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/UpstreamRequestBalancer.java
- changelog.yaml
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTestBase.java
- client-tests/src/test/java/ru/hh/jclient/common/HttpClientFactoryBuilderTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/RequestBalancerBuilderTest.java
- client/src/main/java/ru/hh/jclient/common/DefaultEngineBuilder.java
- client/src/main/java/ru/hh/jclient/common/HttpClientFactoryBuilder.java
- client/src/main/java/ru/hh/jclient/common/RequestEngineBuilder.java
https://jira.hh.ru/browse/HH-204658
> HH-204658 merge master

- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
https://jira.hh.ru/browse/HH-186757
**version change** PATCH
**description**: optimise logs
**requires_changes_in_hh**: false
**instructions**:
> HH-186757 optimise logs

- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
**version change** : PATCH
**description**: fix npe
**requires_changes_in_hh** : false
**instructions** :
> HH-188603 fix npe

- .github/PULL_REQUEST_TEMPLATE.md
- .hh-release.yaml
- balancing/pom.xml
- balancing/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/DowntimeDetector.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/RequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/ResponseTimeTracker.java
- changelog.yaml
- client-errors/pom.xml
- client-maven-enforcer/pom.xml
- client-metrics/pom.xml
- client-testbase/pom.xml
- client-tests/pom.xml
- client-tests/src/test/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategyTest.java
- client-utils/pom.xml
- client/pom.xml
- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
- jclient-common-api/pom.xml
- pom.xml
https://jira.hh.ru/browse/HH-207094
> HH-207094 sync with master & up public-pom

- client/src/main/java/ru/hh/jclient/common/HttpClientImpl.java
> HH-208528 catch exceptions in onThrowable and complete CF

- balancing/src/main/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategy.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/DowntimeDetector.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Server.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategyTest.java
> [!IMPORTANT] 
> Добавь в описание PR changelog в формате:
> HH-210117 pretty logging for adaptive balancing + unit test

- client/pom.xml
- client/src/main/java/ru/hh/jclient/common/util/ContentType.java
- pom.xml
> HH-210442 remove jsr305

- client-errors/pom.xml
- client-metrics/pom.xml
- pom.xml
> Hh 211131 update dependencies

- client-metrics/pom.xml
changelog: not relevant
https://jira.hh.ru/browse/HH-211277
> HH-211277 use jakarta version for nab-metrics

- balancing/pom.xml
- client-errors/pom.xml
- client-maven-enforcer/pom.xml
- client-metrics/pom.xml
- client-testbase/pom.xml
- client-tests/pom.xml
- client-utils/pom.xml
- client/pom.xml
- jclient-common-api/pom.xml
- pom.xml
> HH-213319 up public-pom and consul-client

- balancing/pom.xml
- client-errors/pom.xml
- client-maven-enforcer/pom.xml
- client-metrics/pom.xml
- client-testbase/pom.xml
- client-tests/pom.xml
- client-utils/pom.xml
- client/pom.xml
- jclient-common-api/pom.xml
- pom.xml
> HH-214596 up public-pom

- .hh-release.yaml
- balancing/src/main/java/ru/hh/jclient/common/balancing/Server.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/ServerEntry.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/Upstream.java
- balancing/src/main/java/ru/hh/jclient/common/balancing/UpstreamRequestBalancer.java
- balancing/src/main/java/ru/hh/jclient/consul/UpstreamServiceImpl.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTest.java
- client-tests/src/test/java/ru/hh/jclient/common/BalancingClientTestBase.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/AbstractBalancingStrategyTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/AdaptiveBalancingStrategyTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/BalancingConcurrencyIntegrationTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/BalancingUpstreamManagerTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/BalancingWorkloadModelTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/ServerTest.java
- client-tests/src/test/java/ru/hh/jclient/common/balancing/UpstreamTest.java
- client-tests/src/test/java/ru/hh/jclient/common/bench/BalancingPerformanceBenchmark.java
- client-tests/src/test/java/ru/hh/jclient/common/bench/CustomizationBenchmark.java
- client/src/main/java/ru/hh/jclient/common/HttpClient.java
- client/src/main/java/ru/hh/jclient/common/RequestContext.java
> [!IMPORTANT] 
> Добавь в описание PR changelog в формате:
> HH-214576 add dest host to request

- balancing/src/main/java/ru/hh/jclient/common/balancing/PropertyKeys.java
- balancing/src/main/java/ru/hh/jclient/consul/UpstreamServiceConsulConfig.java
- balancing/src/main/java/ru/hh/jclient/consul/UpstreamServiceImpl.java
- client-tests/src/test/java/ru/hh/jclient/consul/UpstreamServiceImplTest.java
> HH-236452 add ignoreNoServersInUpstreams setting
